### ISSUE TITLE
ERROR: "The ODBC adapter expects exactly one connection string"

### ISSUE THREAD

**Issue by Bento-HS** [tconbeer/harlequin-odbc#21]
Hi, I'm attempting to migrate from Azure Data Studio to Harlequin and am receiving this error with the odbc connection.

![Image](https://github.com/user-attachments/assets/8750bd77-33d6-446c-bdb3-84864d8e3a17)

It looks to me like the connection string cannot use spaces, which makes sense as the config setup says this:

![Image](https://github.com/user-attachments/assets/335895f5-dabf-44df-84bc-5bd68190e6cf)

However the example on [harlequin.sh](https://harlequin.sh/docs/odbc) has spaces in its driver parameter, so I would assume that means this _should_ be valid setup:

![Image](https://github.com/user-attachments/assets/eee6e805-c564-471b-a274-dd99abbf5294)

So, I'm a bit lost as to whether I'm doing this right or not. 

System Info:

- System OS: Win 10 Enterprise
- Terminal: Wezterm
- Shell: Clink

**Comment by tconbeer** [comment]
This is a bug in `harlequin --config` -- it should be more clear that if your connection string has spaces, it needs to be wrapped in quotes, and then it needs to respect the quotes instead of splitting inside them. I think you did something similar to this, note that the generated conn str is a list of many strings:

![Image](https://github.com/user-attachments/assets/b58ad07f-0607-455d-8023-bc167eb566b1)

Unfortunately adding single quotes doesn't help:

![Image](https://github.com/user-attachments/assets/5a2a3615-85ae-4d99-8f7c-6638c7b9ce85)

Nor double quotes:

![Image](https://github.com/user-attachments/assets/b30c761f-6f2b-40ca-b4b4-e86182c0f32d)

What does work is manually editing the TOML config file, and including your connection string there (you do not need to nest quotes):

```toml
[profiles.odbc]
adapter = "odbc"
theme = "harlequin"
limit = 10000
keymap_name = ["vscode"]
conn_str = ["Driver={ODBC Driver 18 for SQL Server};Server=tcp:localhost,1433;Database=dev;Uid=sa;Pwd={for-testing};Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;"]
```
